# Generated by Django 3.2 on 2021-05-01 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sha256', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hash',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
